### ISSUE TITLE
[Bug] Benchmark fails with "ignored.includes is not a function"

### ISSUE THREAD

**Issue by platienum** [architect/aws-lite-benchmarks#3]
## Describe the bug

Benchmark fails with error:

```console
file:///local/home/platienum/workspace/aws-lite-performance/node_modules/@aws-lite/s3/src/lib.mjs:84
    if (paramMappings[normalized] && !ignored.includes(normalized)) {
                                              ^

TypeError: @aws-lite/client: S3.PutObject: ignored.includes is not a function
    at file:///local/home/platienum/workspace/aws-lite-performance/node_modules/@aws-lite/s3/src/lib.mjs:84:47
    at Array.reduce (<anonymous>)
    at Object.parseHeadersToResults [as response] (file:///local/home/platienum/workspace/aws-lite-performance/node_modules/@aws-lite/s3/src/lib.mjs:75:41)
    at Object.PutObject (/local/home/platienum/workspace/aws-lite-performance/node_modules/@aws-lite/client/src/client-factory.js:172:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateCharts (file:///local/home/platienum/workspace/aws-lite-performance/bench/generate-charts.mjs:156:5) {
  service: 's3',
  property: 'S3',
  awsDoc: 'https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html',
  readme: 'https://aws-lite.org/services/s3#putobject'
}
```

## Steps to reproduce

Follow instructions in https://github.com/architect/aws-lite-performance/#reproduction

#### Observed behavior

Benchmark fails to run because of a bug in `@aws-lite/client`

#### Expected behavior

Benchmark runs successfully.

**Comment by ryanblock** [comment]
Fix verified (https://github.com/architect/aws-lite-performance/actions/runs/7189544166/job/19618237047), thanks for reporting @platienum!
